apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librimem-config-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Erinbro/librimem-config.git
    targetRevision: HEAD
    path: ./kube
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true


