apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librimem-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Erinbro/librimem-config.git
    targetRevision: HEAD
    path: kube
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
