apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: librimem.online
spec:
  secretName: librimem.online
  dnsNames:
    - librimem.online
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
