apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImFtOXpaVzFoWjI1bE9rUkhhVzFoWkZOelZBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
