apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: josemagne/users:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
      imagePullSecrets:
        - name: regcred
