apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: librimem-certifcate
  namespace: cert-manager
spec:
  dnsNames:
    - librimem.online
  secretName: selfsigned-cert-tls
  issuerRef:
    name: selfsigned-issuer
